version: "2"
services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
  server:
    build:
      context: .
    command: nodemon --legacy-watch index.js
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
