version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  server:
    build:
      context: ./
    command: nodemon index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
